print("Welcome to the Soccer Tracker!")
name = input("What is your name?")
age = input("How old are you?")
print("Select your position:")
print("1. LW/RW")
print("2. CAM")
print("3. CDM")
print("4. CM")
print("5. LM/RM")
print("6. CB")
print("7. LB/RB")
position = input("Your Position: ")
foot = input("What's your dominant foot?: ")
print("Now, rate yourself out of 10 on the following skills:")
dribbling = input("1. Dribbling:")
shooting = input("2. Shooting/Finishing:")
passing = input("3. Passing:")
stamina = input("4. Stamina:")
speed = input("5. Speed:")
defending = input("6. Defending:")
iq = input("7. Soccer IQ:")


print("FINAL RESULTS")
print(f"NAME: {name.upper()}")
print(f"AGE: {age}")
print(f"POSITION: {position.upper()}")
print(f"DOMINANT FOOT: {foot.upper()}")
print("SKILLS")
print(f"1.DRIBBLING: {dribbling}")
print(f"2.SHOOTING/FINISHING: {shooting}")
print(f"3.PASSING: {passing}")

