print("Welcome to the Soccer Tracker!")
print(input("What is your name?"))
print(input("How old are you?"))
print("Select your position:")
print("1. LW/RB")
print("2. CAM")
print("3. CDM")
print("4. CM")
print("5. LM/RM")
print("6. CB")
print("7. LB/RB")
position = input("Your Position: ")
print("What is Your dominant doot?")
print("1. Right")
print("2. Left")
dom_foot = input("Your dominant foot is: ")
print("Now, rate yourself out of 10 on the following skills:")
print(input("1. Dribbling:"))
print(input("2. Shooting/Finishing:"))
print(input("3. Passing:"))
print(input("4. Stamina:"))
print(input("5. Speed:"))
print(input("6. Defending:"))
print(input("7. Soccer IQ:"))

